INSERT INTO Plans(name, price, applyLimit, postLimit)
VALUES ('User Basic', 0, 0, 0),
       ('User Prime', 10, 5, 0),
       ('User Gold', 20, NULL, 0),
       ('Employer Prime', 50, 0, 5),
       ('Employer Gold', 100, 0, NULL);

INSERT INTO Users (userID,
                   planID,
                   email,
                   password,
                   userType,
                   dateCreated,
                   isActive,
                   balance,
                   isAutomatic)
VALUES ('gordon',
        1,
        'gordon@comp353.com',
        'gordon',
        'employee',
        '2020-01-15',
        TRUE,
        0,
        TRUE),
       ('tiffany',
        2,
        'tiffany@comp353.com',
        'tiffany',
        'employee',
        '2020-02-15',
        TRUE,
        10,
        FALSE),
       ('arun',
        3,
        'arun@comp353.com',
        'arun',
        'employee',
        '2020-03-15',
        TRUE,
        -10,
        FALSE),
       ('leo',
        4,
        'leo@comp353.com',
        'leo',
        'employer',
        '2020-04-15',
        FALSE,
        0,
        TRUE),
       ('bob',
        5,
        'bob@comp353.com',
        'bob',
        'employer',
        '2020-05-15',
        TRUE,
        -100,
        FALSE),
       ('alice',
        NULL,
        'alice@comp353.com',
        'alice',
        'admin',
        '2020-06-15',
        TRUE,
        0,
        TRUE);

INSERT INTO Job_Categories_List(categoryName)
VALUES ('Human Resources'),
       ('Software Developer'),
       ('Business Analyst'),
       ('IT Help Desk'),
       ('System Administrator'),
       ('Database Administrator');
