INSERT INTO Plans(name, price, applyLimit, postLimit, userType)
VALUES ('Employee Basic', 0, 0, 0, 'employee'),
       ('Employee Prime', 10, 5, 0, 'employee'),
       ('Employee Gold', 20, NULL, 0, 'employee'),
       ('Employer Prime', 50, 0, 5, 'employer'),
       ('Employer Gold', 100, 0, NULL, 'employer'),
       ('Admin', 0, 0, 0, 'admin');

INSERT INTO Users (userID,
                   planID,
                   email,
                   password,
                   dateCreated,
                   isActive,
                   balance,
                   isAutomatic)
VALUES ('gordon',
        1,
        'gordon@comp353.com',
        'gordon',
        '2020-01-15',
        TRUE,
        0,
        TRUE),
       ('tiffany',
        2,
        'tiffany@comp353.com',
        'tiffany',
        '2020-02-15',
        TRUE,
        10,
        FALSE),
       ('arun',
        3,
        'arun@comp353.com',
        'arun',
        '2020-03-15',
        TRUE,
        10,
        FALSE),
       ('leo',
        4,
        'leo@comp353.com',
        'leo',
        '2020-04-15',
        FALSE,
        0,
        TRUE),
       ('bob',
        5,
        'bob@comp353.com',
        'bob',
        '2020-05-15',
        TRUE,
        -100,
        FALSE),
       ('alice',
        6,
        'alice@comp353.com',
        'alice',
        '2020-06-15',
        TRUE,
        0,
        TRUE),
       ('tyson',
        2,
        'tyson@comp353.com',
        'tyson',
        '2020-03-15',
        TRUE,
        -10,
        TRUE);

INSERT INTO Job_Categories_List(categoryName)
VALUES ('Human Resources'),
       ('Software Developer'),
       ('Business Analyst'),
       ('IT Help Desk'),
       ('System Administrator'),
       ('Database Administrator');

INSERT INTO Payment_Methods(userID, isPreSelected, cardNumber, paymentType)
VALUES ('gordon', FALSE, 1234, 'debit'),
       ('tiffany', TRUE, 1112, 'credit'),
       ('arun', TRUE, 1718, 'credit'),
       ('leo', TRUE, 2324, 'debit'),
       ('bob', FALSE, 2930, 'credit'),
       ('tyson', TRUE, 3536, 'debit');
